## Day 11 (30/05/2025)

## numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Adding and removing Elements

In [4]:
a=np.append(arr, [[10, 11, 12]])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
a=np.insert(arr,2,[1,2,3])
a

array([1, 2, 1, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[10,11,12]])
arrdelete=np.delete(arr,1,axis=0) #Row wise delete at index 1(4,5,6)
print(arrdelete)
arrdelete=np.delete(arr,1,axis=1) #column wise delete at index 1(2,5,11)
print(arrdelete)



[[ 1  2  3]
 [10 11 12]]
[[ 1  3]
 [ 4  6]
 [10 12]]


### Combining & spliting

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[11,12,13],[14,15,16]])
np.concatenate((arr1,arr2),axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [12]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [26]:
arr1=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
arr2=np.array([[[[11,12,13],[14,15,16],[17,18,19]]]])
np.concatenate((arr1,arr2),axis=3)

array([[[[ 1,  2,  3, 11, 12, 13],
         [ 4,  5,  6, 14, 15, 16],
         [ 7,  8,  9, 17, 18, 19]]]])

In [37]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr)
np.split(arr,2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [38]:
np.hsplit(arr,6)

[array([[1],
        [7]]),
 array([[2],
        [8]]),
 array([[3],
        [9]]),
 array([[ 4],
        [10]]),
 array([[ 5],
        [11]]),
 array([[ 6],
        [12]])]

### Indexing & slicing

In [44]:
print(arr)
print(arr[1,2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
9


In [ ]:
a=np.array([1,2,3])
print(a[2])

3

In [ ]:
a[2]=7
print(a)

array([1, 2, 7])

In [49]:
print(arr[1,3])
arr[1,3]=100
print(arr)

10
[[  1   2   3   4   5   6]
 [  7   8   9 100  11  12]]


In [50]:
print(a[0:2])

[1 2]


In [ ]:
print(arr)
print(arr[0:2,4]) 

[[  1   2   3   4   5   6]
 [  7   8   9 100  11  12]]
[ 5 11]


In [55]:
arr[:1]

array([[1, 2, 3, 4, 5, 6]])

In [56]:
arr[:,1]

array([2, 8])

In [57]:
arr<5

array([[ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False]])

### indexing and Slicing

In [ ]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print((arr1<6)&(arr2>11))#True if both the condition is true
print((arr1<6)|(arr2>11))#True if atleast one condition is true

[[False  True  True]
 [ True  True False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [62]:
arrbool=np.array([True,False,True])
~arrbool

array([False,  True, False])

In [64]:
print(arr,'\n')
print(arr[arr<5])

[[  1   2   3   4   5   6]
 [  7   8   9 100  11  12]] 

[1 2 3 4]


### Scalar Math

In [66]:
print(arr,"\n")

[[  1   2   3   4   5   6]
 [  7   8   9 100  11  12]] 



In [68]:
print(np.add(arr,2))

[[  3   4   5   6   7   8]
 [  9  10  11 102  13  14]]


In [69]:
print(np.subtract(arr,2))

[[-1  0  1  2  3  4]
 [ 5  6  7 98  9 10]]


In [70]:
print(np.multiply(arr,2))

[[  2   4   6   8  10  12]
 [ 14  16  18 200  22  24]]


In [71]:
print(np.divide(arr,2))

[[ 0.5  1.   1.5  2.   2.5  3. ]
 [ 3.5  4.   4.5 50.   5.5  6. ]]


In [74]:
print(np.power(arr,2))

[[    1     4     9    16    25    36]
 [   49    64    81 10000   121   144]]


### Vector Math

In [75]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[11,12,13],[14,15,16],[17,18,19]])
np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [76]:
np.subtract(arr1,arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [77]:
np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [78]:
np.divide(arr1,arr2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [79]:
np.power(arr1,arr2)

array([[          1,        4096,     1594323],
       [  268435456,   452807053,  -683606016],
       [-2094633337,           0,  -400556711]])

In [84]:
a=np.array([1,2,3])
b=np.array([1,4,3])
np.array_equal(a, b)

False

In [85]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [86]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [87]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [91]:
a=np.array([-1, -2, -3])
np.abs(a)

array([1, 2, 3])

In [95]:
a=np.array([1.2, 2.5, 3])
print(np.ceil(a))
print(np.floor(a))
print(np.round(a))

[2. 3. 3.]
[1. 2. 3.]
[1. 2. 3.]


### Statistics

In [97]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.mean(a,axis=0))  # Mean of each column
print(np.mean(a,axis=1))  # Mean of each row

[4. 5. 6.]
[2. 5. 8.]


In [ ]:
print(a.sum())  # Sum of all elements
print(a.sum(axis=0))  # Sum of each column
print(a.sum(axis=1))  # Sum of each row


45
[12 15 18]
[ 6 15 24]


In [104]:
print(arr)
print("min =",arr.min())  # Minimum value in the array
print("Max =",arr.max())  # Maximum value in the array
print("minimum in each column =",arr.min(axis=0))  # Minimum value in each column
print("minimum in each row =",arr.max(axis=1))  # Maximum value in each row

[[  1   2   3   4   5   6]
 [  7   8   9 100  11  12]]
min = 1
Max = 100
minimum in each column = [1 2 3 4 5 6]
minimum in each row = [  6 100]


In [113]:
print(arr,"\n")
print(np.std(arr,axis=0))  # Standard deviation of each column
print(np.std(arr,axis=1))  # Standard deviation of each row
print(np.var(arr,axis=0))  # Variance of each column
print(np.var(arr,axis=1))  # Variance of each row
print("variance ",np.var(arr))  # Variance of the entire array
print("standard deviation ",np.std(arr))  # Standard deviation of the entire array
print("Correlation coefficient = ")
print(np.corrcoef(arr))  # Correlation coefficient matrix


[[  1   2   3   4   5   6]
 [  7   8   9 100  11  12]] 

[ 3.  3.  3. 48.  3.  3.]
[ 1.70782513 33.80705055]
[   9.    9.    9. 2304.    9.    9.]
[   2.91666667 1142.91666667]
variance  683.1666666666666
standard deviation  26.1374571576247
Correlation coefficient = 
[[1.         0.18041726]
 [0.18041726 1.        ]]
