## Day 10 (29-05-2025)

## Numpy

In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.2 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/12.6 MB 1.2 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.6 MB 1.1 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/12.6 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.6/12.6 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.1 MB/s eta 0:00:11
   ------ --------------------------------- 2.1/12.6 MB 1.1 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/12.6 MB 1.1 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.6 MB 991.2 kB/s eta 0:00:11
   ------- -------------------------------- 2.4/12.6 MB 991.2 kB/s eta 0:00:11
   ------


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

### #Creating Arrays

In [ ]:
# Create a 1D NumPy array
arr_1d=np.array([1,2,3])
arr_1d

array([1, 2, 3])

In [ ]:
# Create a 2D NumPy array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [13]:
# numpy vs list array
l=[1,2,3]
print(f"list multiplication = {2*l}\n")
a=np.array([1,2,3])
print(f"numpy array multiplication = {a*2}")

list multiplication = [1, 2, 3, 1, 2, 3]

numpy array multiplication = [2 4 6]


In [17]:
#1d array of length 3 with zeros
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [18]:
# 2D array of shape (3,4) with zeros
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
#5*5 identity matrix
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#one dimensional array of ones
arr=np.ones(3)
print("One dimensional array of ones\n")
print(arr,'\n')
# 2D array of ones with shape (3,4)
arr = np.ones((3,4))
print("2D array of ones with shape (3,4)\n")
print(arr)

One dimensional array of ones

[1. 1. 1.] 

2D array of ones with shape (3,4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
arr = np.linspace(0,100,6)
print("1D array with 6 evenly spaced values between 0 and 100\n")
print(arr)

1D array with 6 evenly spaced values between 0 and 100

[  0.  20.  40.  60.  80. 100.]


In [31]:
arr=np.arange(0,10,3)
print("1D array with values from 0 to 10 with a step of 3\n")
print(arr)

1D array with values from 0 to 10 with a step of 3

[0 3 6 9]


In [32]:
arr = np.full((2,3),8)
print("2D array of shape (2,3) with all values set to 8\n")
print(arr)

2D array of shape (2,3) with all values set to 8

[[8 8 8]
 [8 8 8]]


In [5]:
arr = np.random.rand(4,5)
print("2D array of shape (4,5) with random values between 0 and 1\n")
print(arr)


2D array of shape (4,5) with random values between 0 and 1

[[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882]
 [0.2160895  0.97627445 0.00623026 0.25298236 0.43479153]
 [0.77938292 0.19768507 0.86299324 0.98340068 0.16384224]
 [0.59733394 0.0089861  0.38657128 0.04416006 0.95665297]]


In [38]:
arr = np.random.rand(2,3)*100
print("2D array of shape (2,3) with random values between 0 and 100\n")
print(arr)

2D array of shape (2,3) with random values between 0 and 100

[[17.24715447 77.05766213 57.03810898]
 [89.88945905 57.71398508 33.59983269]]


In [42]:
arr = np.random.randint(5, size=(2,3))
print("2D array of shape (2,3) with random integers between 0 and 4\n")
print(arr)

2D array of shape (2,3) with random integers between 0 and 4

[[4 3 0]
 [3 3 3]]


### #inspecting properties

In [ ]:

arr= np.array([[1,2,3],[4,5,6]])
# print("Shape of the array:", arr.shape)
print(arr.astype(dtype=int))


[[1 2 3]
 [4 5 6]]


In [60]:
print(arr.tolist())

[[1, 2, 3], [4, 5, 6]]


In [67]:
print(np.info(np.eye))

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If 

In [62]:
print(arr.size)

6


In [63]:
print(arr.shape)

(2, 3)


In [68]:
print(arr.dtype)

int64


### #copying,sorting,& reshaping

In [71]:
copy_arr = arr.copy()
print("Copied array:")
print(copy_arr)


Copied array:
[[1 2 3]
 [4 5 6]]


In [110]:
print(arr.view(dtype=int))

[[1 2 3]
 [4 5 6]]


In [95]:
a= np.array([[1,2,3],[7,2,3]])
a.sort()
print(a)

[[1 2 3]
 [2 3 7]]


In [108]:
ar= np.array([[100,90,3],
            [24,100,6]])
ar.sort(axis=0) # Sort along the first axis (columns)
print(ar)
ar.sort(axis=1) # Sort along the second axis (rows)
print("\n",ar)

[[ 24  90   3]
 [100 100   6]]

 [[  3  24  90]
 [  6 100 100]]


In [117]:
ar_2d= np.array([[1,2,3],[4,5,6]])
print("Original array:\n")
print(ar_2d)
ar_1d=ar_2d.flatten()  # Flatten the array to 1D
print("\nFlattened array:\n")
print(ar_1d)

Original array:

[[1 2 3]
 [4 5 6]]

Flattened array:

[1 2 3 4 5 6]


In [80]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [82]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1.resize((3,5))
print(arr1)

[[1 2 3 4 5]
 [6 0 0 0 0]
 [0 0 0 0 0]]
