In [1]:
import numpy as np

In [17]:
np.random.seed(2)  # Set seed for reproducibility (value repeated)
arr = np.random.randint(0, 10, 5)
print(arr)

[8 8 6 2 8]


In [24]:
arr =np.array([[1, 2, 3],
               [4, 5, 6]],dtype = np.int64)
print(arr)
print("Data Type = ",arr.dtype)  # Print the data type of the array
print("Shape = ",arr.shape)  # Print the shape of the array
print("Dimension = ",arr.ndim)   # Print the number of dimensions of the array
print("Array Size = ",arr.size)   # Print the total number of elements in the array
print("Item Size =",arr.itemsize)  # Print the size in bytes of each element in the array

[[1 2 3]
 [4 5 6]]
Data Type =  int64
Shape =  (2, 3)
Dimension =  2
Array Size =  6
Item Size = 8


### Type conversion

In [28]:
arr =np.array([[1, 2, 3],
               [4, 5, 6]],dtype = np.int32)
print(arr)
print("Data Type = ",arr.dtype)  # Print the data type of the array
arr = arr.astype(np.float64)  # Convert the array to float64 type
print(arr)
print("Data Type = ",arr.dtype)  # Print the data type of the array after conversion


[[1 2 3]
 [4 5 6]]
Data Type =  int32
[[1. 2. 3.]
 [4. 5. 6.]]
Data Type =  float64


In [30]:
arr1 =np.array([[1, 2, 3],
               [4, 5, 6]])
arr2 = np.array([1,2,3])
print("Array1+Array2 =")
print(arr1+arr2)

Array1+Array2 =
[[2 4 6]
 [5 7 9]]
