NumPy

In [2]:
import numpy as np
import pandas as pd

1.Create a 1D array from a list.


In [3]:
list = [1,2,3,4,5]
arr = np.array(list)
print(arr)

[1 2 3 4 5]


2. Create a 3x3 array of zeros.


In [4]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Create a 2x2 array of ones.

In [5]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

4. Generate array from 0 to 10 (exclusive).

In [6]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5. Create 5 evenly spaced numbers between 0 and 1.


In [7]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 4x4 identity matrix.

In [8]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. Reshape 1D array to 2D.

In [9]:
arr1d= np.array([1,2,3,4])
print(arr1d)

arr2d = arr1d.reshape((2,2))
arr2d

[1 2 3 4]


array([[1, 2],
       [3, 4]])

8. Get the shape and dtype of an array.

In [10]:
print(arr2d.shape)
print(arr1d.dtype)

(2, 2)
int64


9. Reverse a NumPy array.

In [11]:
arr2d = np.array([1,2,3])
print(arr2d)
revarr = arr2d[::-1]
revarr

[1 2 3]


array([3, 2, 1])

10. Extract even numbers from an array.

In [12]:
arr = np.array([0,2,3,4,2,6,9,7,8])
n = arr.size
evenarr =arr[arr%2==0]
print(evenarr)


[0 2 4 2 6 8]


11. Find the max in each row.

In [13]:
arr = np.array([[1,2,3],[11,23,12]])
print(arr)
max = arr.max(axis = 1)  # Max along rows
print("Maximum elements along rows:", max)

[[ 1  2  3]
 [11 23 12]]
Maximum elements along rows: [ 3 23]


12. Compute the mean, std, and median of an array.


In [14]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr1d =[1,2,3,4,5,6,7]
print("Array 1D: ", arr1d)
print("Array : \n",arr2d)
print(f"Mean of arr2d: {arr2d.mean()}")
print(f"median of arr2d: {np.median(arr1d)}")
print(f"standard deviation of arr2d: {arr2d.std()}")

Array 1D:  [1, 2, 3, 4, 5, 6, 7]
Array : 
 [[1 2 3]
 [4 5 6]]
Mean of arr2d: 3.5
median of arr2d: 4.0
standard deviation of arr2d: 1.707825127659933


13. Stack two arrays vertically.

In [15]:
arr1 = np.array([11,23,12])
arr2 = np.array([20,30,40])
stack_arr = np.stack((arr1,arr2),axis=1)
print("Stacked array along vertically:\n", stack_arr)

Stacked array along vertically:
 [[11 20]
 [23 30]
 [12 40]]


14. Stack two arrays horizontally.

In [16]:
stack_arrh =np.stack((arr1,arr2),axis=0)
print(stack_arrh)

[[11 23 12]
 [20 30 40]]


15. Stack two arrays horizontally.


In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
stack_arrh =np.stack((arr1,arr2),axis=0)
print(stack_arrh)

[[1 2 3]
 [4 5 6]]


16. Find the unique values and their counts.


In [18]:
arr = np.array([1,2,3,4,5,1,2,3,1,2,3,2,2])
# unique_arr = np.unique(arr)
unique,count= np.unique(arr, return_counts=True)
# print("Unique elements in the array:", unique_arr)
print("Unique elements in the array:", unique)
print("Counts of unique elements:", count)


Unique elements in the array: [1 2 3 4 5]
Counts of unique elements: [3 5 3 1 1]


17. Replace NaN with column means.


In [19]:
arr = np.array([[1,np.nan,3,4,5],[1,2,np.nan,4,5],[1,3,3,4,5]])
print("Original array with NaN values:\n", arr)
print("Array after replacing NaN with column means:\n", np.where(np.isnan(arr), np.nanmean(arr, axis=0), arr))


Original array with NaN values:
 [[ 1. nan  3.  4.  5.]
 [ 1.  2. nan  4.  5.]
 [ 1.  3.  3.  4.  5.]]
Array after replacing NaN with column means:
 [[1.  2.5 3.  4.  5. ]
 [1.  2.  3.  4.  5. ]
 [1.  3.  3.  4.  5. ]]


18. Get index of min and max values.


In [20]:
arr = np.array([1,2,3,4,5,0,-3,44])
print("Original array:", arr)
# index of Minimum value in the array
min_value_index = np.argmin(arr)
print("Index of minimum value in the array:", min_value_index)
# index of Maximum value in the array
max_value_index = np.argmax(arr)
print("Index of maximum value in the array:", max_value_index)


Original array: [ 1  2  3  4  5  0 -3 44]
Index of minimum value in the array: 6
Index of maximum value in the array: 7


19. Create a 3D array of random integers.



In [21]:
arr3d = np.random.randint(0, 10, (3, 3, 2))
arr3d


array([[[7, 8],
        [3, 4],
        [7, 8]],

       [[9, 0],
        [6, 9],
        [0, 6]],

       [[5, 4],
        [7, 5],
        [6, 5]]], dtype=int32)

20. Use np.where() to replace values


In [22]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(np.where(arr2d > 5,arr2d,0))

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 6]]


Pandas

1. Create a Series using a Python list.


In [23]:
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


2. Create a Series with custom string indices.




In [24]:
data =[1,2,3,4,5]
s1 = pd.Series(data,index=['a','b','c','d','e'])
print(s1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


3. Create a Series from a dictionary.


In [25]:
dict = {'a':1,'b':2,'c':3}
s2 = pd.Series(dict)
print(s2)

a    1
b    2
c    3
dtype: int64


4. Access first 3 elements of a Series.


In [26]:
s3 = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s3)
print('\n First 3 elements of the Series:\n')
s3.head(3)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

 First 3 elements of the Series:



0    1
1    2
2    3
dtype: int64

5. Filter Series elements greater than 50.



In [27]:
s= pd.Series([1,2,3,4,50,55,6,7,80,90,10])
print("Original Series:\n", s)
print("Elements greater than 50:\n",s[s>50])

Original Series:
 0      1
1      2
2      3
3      4
4     50
5     55
6      6
7      7
8     80
9     90
10    10
dtype: int64
Elements greater than 50:
 5    55
8    80
9    90
dtype: int64


6. Add two Series with different indices.



In [28]:
s1 =pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10,11,12])
s3 = s1 + s2
print("Sum of two Series:\n", s3)

Sum of two Series:
 0     7.0
1     9.0
2    11.0
3    13.0
4    15.0
5     NaN
6     NaN
dtype: float64


In [29]:
s1.add(s2, fill_value=0)  # Adding with fill_value for different lengths

0     7.0
1     9.0
2    11.0
3    13.0
4    15.0
5    11.0
6    12.0
dtype: float64


7. Multiply a Series by a scalar.


In [30]:
series = pd.Series([1,2,3,4,5])
print("Original Series:\n", series)
print("series multiply by 2:\n",series*2)

Original Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
series multiply by 2:
 0     2
1     4
2     6
3     8
4    10
dtype: int64


8. Use .multiply() method to multiply with scalar.


In [31]:
s = pd.Series([1,2,3,4,5])
s.multiply(2)

0     2
1     4
2     6
3     8
4    10
dtype: int64

10. Sort Series by values descending.


In [32]:
s = pd.Series([1,20,30,4,5])
print("Original Series:\n", s)
print("sorted series: \n",s.sort_values())

Original Series:
 0     1
1    20
2    30
3     4
4     5
dtype: int64
sorted series: 
 0     1
3     4
4     5
1    20
2    30
dtype: int64


11. Sort Series by index.


In [33]:
s = pd.Series([1,2,3,4,5],index = [1,2,4,5,3])
print("Original Series with custom index:\n", s)
print("Sorted Series by index:\n", s.sort_index())

Original Series with custom index:
 1    1
2    2
4    3
5    4
3    5
dtype: int64
Sorted Series by index:
 1    1
2    2
3    5
4    3
5    4
dtype: int64


12. Check for null values.



14. Concatenate two Series using concat().


15. Concatenate two Series using append().


16. Retrieve first 5 elements using .head()



17. Retrieve last 5 elements using .tail()


18. Convert Series to DataFrame.


19. Replace NaN with 0.


20. Drop missing values.


21. Check Series data type.

